version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432" # Открываем порт для доступа к БД с хост-машины
    environment:
      POSTGRES_USER: root # Имя пользователя для подключения к БД
      POSTGRES_PASSWORD: ozon # Пароль пользователя
      POSTGRES_DB: generation # Название базы данных, которую нужно создать
    volumes:
      - ./data:/var/lib/postgresql/data # Монтируем директорию на хост-машине, где будут храниться данные БД
