// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: converter.proto

package handlers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestGetLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenUrl string `protobuf:"bytes,1,opt,name=shorten_url,json=shortenUrl,proto3" json:"shorten_url,omitempty"`
}

func (x *RequestGetLink) Reset() {
	*x = RequestGetLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetLink) ProtoMessage() {}

func (x *RequestGetLink) ProtoReflect() protoreflect.Message {
	mi := &file_converter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetLink.ProtoReflect.Descriptor instead.
func (*RequestGetLink) Descriptor() ([]byte, []int) {
	return file_converter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetLink) GetShortenUrl() string {
	if x != nil {
		return x.ShortenUrl
	}
	return ""
}

type ResponseGetLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialUrl string `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
}

func (x *ResponseGetLink) Reset() {
	*x = ResponseGetLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetLink) ProtoMessage() {}

func (x *ResponseGetLink) ProtoReflect() protoreflect.Message {
	mi := &file_converter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetLink.ProtoReflect.Descriptor instead.
func (*ResponseGetLink) Descriptor() ([]byte, []int) {
	return file_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGetLink) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

type RequestGeneration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialUrl string `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
}

func (x *RequestGeneration) Reset() {
	*x = RequestGeneration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGeneration) ProtoMessage() {}

func (x *RequestGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_converter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGeneration.ProtoReflect.Descriptor instead.
func (*RequestGeneration) Descriptor() ([]byte, []int) {
	return file_converter_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGeneration) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

type ResponseGeneration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenUrl string `protobuf:"bytes,1,opt,name=shorten_url,json=shortenUrl,proto3" json:"shorten_url,omitempty"`
}

func (x *ResponseGeneration) Reset() {
	*x = ResponseGeneration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_converter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGeneration) ProtoMessage() {}

func (x *ResponseGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_converter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGeneration.ProtoReflect.Descriptor instead.
func (*ResponseGeneration) Descriptor() ([]byte, []int) {
	return file_converter_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseGeneration) GetShortenUrl() string {
	if x != nil {
		return x.ShortenUrl
	}
	return ""
}

var File_converter_proto protoreflect.FileDescriptor

var file_converter_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x31, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x34,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x55, 0x72, 0x6c, 0x22, 0x35, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x32, 0x8f, 0x01, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x0d, 0x5a,
	0x0b, 0x2e, 0x2f, 0x3b, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_converter_proto_rawDescOnce sync.Once
	file_converter_proto_rawDescData = file_converter_proto_rawDesc
)

func file_converter_proto_rawDescGZIP() []byte {
	file_converter_proto_rawDescOnce.Do(func() {
		file_converter_proto_rawDescData = protoimpl.X.CompressGZIP(file_converter_proto_rawDescData)
	})
	return file_converter_proto_rawDescData
}

var file_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_converter_proto_goTypes = []interface{}{
	(*RequestGetLink)(nil),     // 0: main.RequestGetLink
	(*ResponseGetLink)(nil),    // 1: main.ResponseGetLink
	(*RequestGeneration)(nil),  // 2: main.RequestGeneration
	(*ResponseGeneration)(nil), // 3: main.ResponseGeneration
}
var file_converter_proto_depIdxs = []int32{
	0, // 0: main.ConverterService.GetLink:input_type -> main.RequestGetLink
	2, // 1: main.ConverterService.Generation:input_type -> main.RequestGeneration
	1, // 2: main.ConverterService.GetLink:output_type -> main.ResponseGetLink
	3, // 3: main.ConverterService.Generation:output_type -> main.ResponseGeneration
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_converter_proto_init() }
func file_converter_proto_init() {
	if File_converter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_converter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_converter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_converter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGeneration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_converter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGeneration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_converter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_converter_proto_goTypes,
		DependencyIndexes: file_converter_proto_depIdxs,
		MessageInfos:      file_converter_proto_msgTypes,
	}.Build()
	File_converter_proto = out.File
	file_converter_proto_rawDesc = nil
	file_converter_proto_goTypes = nil
	file_converter_proto_depIdxs = nil
}
